/* AI practice lifecycle. The original peer/manual mode remains available. */
(function(){
'use strict';
const old={render,sync,canAct,cardData,enterGame,startTurn,aiTurn,aiCheckKO,gameOver,slotHTML,handMenu,renderHandActs,playTrainer,toActive,toBench,attach,promote,retreat,ko,fieldMenu,drawN,prizeMenu,bestAttack,canPay,energyGap,calcDmg,coach,closeSheet,attackTargets,playStadium,handTo,fieldTo,attachedView,dmg,tog,searchDeck,pileView,mulligan,extraDraw,useAbility};
const P=window.AIPractice={phase:'idle',epoch:0,paused:false,running:false,speed:650,step:'',pendingPromotion:null,lastDecks:null};
const SAVE='dgpk_ai_session_v2', CACHE='dgpk_card_cache_v2';
const localGet=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback;}catch(e){return fallback;}};
const localSet=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));}catch(e){}};
const clone=value=>JSON.parse(JSON.stringify(value));
const active=()=>ai&&P.phase!=='idle';
const players=()=>[me,opp];
const field=p=>[p.active].concat(p.bench).filter(Boolean);
const cardLabel=c=>c&&c.name||'';
const canPlay=()=>active()&&!ended&&!P.paused&&P.phase==='player'&&turn==='me'&&!me.attacked;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const STARTER_DATA = [{"id":"sv03-026","name":"Charmander","image":"https://assets.tcgdex.net/en/sv/sv03/026","category":"Pokemon","stage":"Basic","hp":60,"types":["Fire"],"attacks":[{"cost":["Fire"],"name":"Heat Tackle","effect":"This Pokémon also does 10 damage to itself.","damage":30}],"weaknesses":[{"type":"Water","value":"×2"}],"retreat":1},{"id":"sv03-027","name":"Charmeleon","image":"https://assets.tcgdex.net/en/sv/sv03/027","category":"Pokemon","stage":"Stage1","hp":90,"types":["Fire"],"evolveFrom":"Charmander","attacks":[{"cost":["Fire","Fire"],"name":"Heat Tackle","effect":"This Pokémon also does 20 damage to itself.","damage":70}],"weaknesses":[{"type":"Water","value":"×2"}],"retreat":2},{"id":"sv03-030","name":"Entei","image":"https://assets.tcgdex.net/en/sv/sv03/030","category":"Pokemon","stage":"Basic","hp":130,"types":["Fire"],"attacks":[{"cost":["Colorless","Colorless","Colorless"],"name":"Blaze Ball","effect":"This attack does 20 more damage for each {R} Energy attached to this Pokémon.","damage":"60+"}],"abilities":[{"type":"Ability","name":"Pressure","effect":"As long as this Pokémon is in the Active Spot, attacks used by your opponent's Active Pokémon do 20 less damage (before applying Weakness and Resistance)."}],"weaknesses":[{"type":"Water","value":"×2"}],"retreat":2},{"id":"sv01-189","name":"Professor's Research","image":"https://assets.tcgdex.net/en/sv/sv01/189","category":"Trainer","effect":"Discard your hand and draw 7 cards.","trainerType":"Supporter"},{"id":"sv01-194","name":"Switch","image":"https://assets.tcgdex.net/en/sv/sv01/194","category":"Trainer","effect":"Switch your Active Pokémon with 1 of your Benched Pokémon.","trainerType":"Item"},{"id":"sv01-196","name":"Ultra Ball","image":"https://assets.tcgdex.net/en/sv/sv01/196","category":"Trainer","effect":"You can use this card only if you discard 2 other cards from your hand.\n\nSearch your deck for a Pokémon, reveal it, and put it into your hand. Then, shuffle your deck.","trainerType":"Item"},{"id":"sv01-198","name":"Youngster","image":"https://assets.tcgdex.net/en/sv/sv01/198","category":"Trainer","effect":"Shuffle your hand into your deck. Then, draw 5 cards.","trainerType":"Supporter"},{"id":"sv01-181","name":"Nest Ball","image":"https://assets.tcgdex.net/en/sv/sv01/181","category":"Trainer","effect":"Search your deck for a Basic Pokémon and put it onto your Bench. Then, shuffle your deck.","trainerType":"Item"},{"id":"sv02-172","name":"Boss's Orders","image":"https://assets.tcgdex.net/en/sv/sv02/172","category":"Trainer","effect":"Switch in 1 of your opponent's Benched Pokémon to the Active Spot.","trainerType":"Supporter"},{"id":"sve-002","name":"Fire Energy","category":"Energy","energyType":"Normal"}];
const NAMES={'sv03-026':'파이리','sv03-027':'리자드','sv03-030':'앤테이','sv01-189':'박사의 연구','sv01-194':'포켓몬 교체','sv01-196':'하이퍼볼','sv01-181':'네스트볼','sv02-172':'보스의 지령','sv01-198':'반바지 꼬마','sve-002':'기본 불꽃 에너지'};
const ATTACK_NAMES={'Heat Tackle':'히트태클','Blaze Ball':'블레이즈볼'};
function seedStarter(){STARTER_DATA.forEach(d=>{enCache[d.id]=clone(d);const k=clone(d);k.name=NAMES[d.id]||d.name;if(k.evolveFrom==='Charmander')k.evolveFrom='파이리';k._lang='en';(k.attacks||[]).forEach(a=>a.name=ATTACK_NAMES[a.name]||a.name);dcache[d.id]=k;});}
seedStarter();
function starterDeck(){const counts={'sv03-026':4,'sv03-027':4,'sv03-030':4,'sv01-189':4,'sv01-194':4,'sv01-196':4,'sv01-181':4,'sv02-172':2,'sv01-198':4,'sve-002':26};const cards={};Object.keys(counts).forEach(id=>{const d=dcache[id];cards[id]={id,name:d.name,img:d.image||'',n:counts[id]};});return {name:'불꽃 스타터 · 60장',cards,lang:'en'};}
P.starterDeck=starterDeck;
// All card operations use bounded requests; a missing card blocks setup, not a running match.
async function getJSON(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(timer);}}
const loadingCards={};
window.cardData=function(id){if(dcache[id])return Promise.resolve(dcache[id]);if(loadingCards[id])return loadingCards[id];const saved=localGet(CACHE,{});if(saved[id]){dcache[id]=saved[id];return Promise.resolve(saved[id]);}
 loadingCards[id]=(async()=>{const pref=localStorage.getItem('dgpk_lang')||'ko';const langs=[pref,'en','ja'].filter((x,i,a)=>a.indexOf(x)===i);for(const lang of langs){try{const d=await getJSON(API+lang+'/cards/'+encodeURIComponent(id));if(!d.name||!d.category)continue;d._lang=lang;dcache[id]=d;if(lang==='en')enCache[id]=d;return d;}catch(e){}}throw Error('카드 정보를 불러오지 못했어요: '+id);})().finally(()=>delete loadingCards[id]);return loadingCards[id];};
function saveCardCache(){const cache=localGet(CACHE,{});Object.keys(dcache).forEach(id=>cache[id]=dcache[id]);const ids=Object.keys(cache);while(ids.length>350)delete cache[ids.shift()];localSet(CACHE,cache);}
async function preload(decks){const ids=[...new Set(decks.flatMap(d=>Object.keys(d.cards)))];let done=0;const queue=ids.slice();await Promise.all(Array.from({length:5},async()=>{while(queue.length){const id=queue.shift();await cardData(id);$('aiLoadStatus').textContent='카드 준비 중 '+(++done)+' / '+ids.length;}}));saveCardCache();}
function validateDeck(deck){if(!deck||!deck.cards)throw Error('덱을 선택해 주세요.');if(Object.values(deck.cards).some(c=>!c.id||!Number.isInteger(c.n)||c.n<1||c.n>60))throw Error('덱의 카드 수량이 올바르지 않아요.');if(deckSize(deck)!==60)throw Error('AI 연습은 60장 덱을 사용해요. 현재 '+deckSize(deck)+'장입니다.');}
async function opponentDeck(mine){const value=$('aiDeckSel').value;if(value==='starter')return starterDeck();if(value==='mirror')return clone(mine);if(value.startsWith('saved:'))return getDecks()[+value.slice(6)];
 const cached=localGet('dgpk_aideck_'+aiLv,null);if(cached){validateDeck(cached);return cached;}
 $('aiLoadStatus').textContent='레벨별 덱 불러오는 중…';const def=AI_DECKS[aiLv],cards={};const queue=def.cards.slice();
 await Promise.all(Array.from({length:4},async()=>{while(queue.length){const entry=queue.shift();const list=await getJSON(API+'en/cards?name='+encodeURIComponent(entry[1]));const exact=Array.isArray(list)?list.filter(c=>c.name.toLowerCase()===entry[1].toLowerCase()):[];const hit=exact.filter(c=>/^(sv|me)/.test(c.id)).pop()||exact.pop();if(!hit)throw Error(entry[1]+' 카드를 찾지 못했어요. 불꽃 스타터 또는 미러전을 선택해 주세요.');cards[hit.id]={id:hit.id,name:hit.name,img:hit.image||'',n:entry[0]};}}));
 const deck={name:def.name,cards};validateDeck(deck);localSet('dgpk_aideck_'+aiLv,deck);return deck;
}
function resetRuntime(){P.epoch++;P.paused=false;P.running=false;P.pendingPromotion=null;P.step='';stopTimer();clearTimeout(koTimer);ended=false;logs=[];turn=null;turnNo=0;closeSheet();$('big').classList.remove('on');}
function deal(p){if(!p.deck.some(isBasic))throw Error(p.nick+'의 덱에 기본 포켓몬이 없어요.');let attempts=0;do{p.deck=shuffle(p.deck.concat(p.hand));p.hand=p.deck.splice(0,7);attempts++;if(attempts>200)throw Error('첫 손패를 만들지 못했어요. 다시 시작해 주세요.');}while(!p.hand.some(isBasic));p.mulligans=attempts-1;p.prizes=p.deck.splice(0,6);p.ready=true;p.turns=0;}
function checkpoint(){if(!active()||ended||P.phase==='loading'||!['setup','player'].includes(P.phase))return;const cache={};players().forEach(p=>p.deck.concat(p.hand,p.prizes,p.discard,p.lost,field(p).flatMap(allCards)).forEach(c=>{if(dcache[c.id])cache[c.id]=dcache[c.id];}));localSet(SAVE,{version:2,phase:P.phase,me,opp,turn,turnNo,aiLv,logs,speed:P.speed,lastDecks:P.lastDecks,cache,at:Date.now()});}
function showResume(){$('resumeAI').classList.toggle('hide',!localGet(SAVE,null));}
function begin(mine,enemy,nick){resetRuntime();solo=true;ai=true;isHost=true;P.phase='setup';me=newPlayer(nick,mine);opp=newPlayer('AI Lv.'+aiLv,enemy);players().forEach(p=>p.deck.forEach(c=>{const d=D(c);if(d){c.name=d.name;c.img=c.img||d.image||'';}}));deal(me);deal(opp);me.bonusDraw=opp.mulligans;opp.bonusDraw=me.mulligans;
 P.lastDecks={mine:clone(mine),enemy:clone(enemy),nick};oppPub=pub(opp);$('lobby').classList.add('hide');$('game').classList.remove('hide');$('mewBtn').classList.remove('hide');$('btnSwap').classList.add('hide');aiDeployBasics();field(opp).forEach(s=>s.turnPlayed=0);sync();chooseStarting();}
$('btnAI').onclick=async function(){if(P.phase==='loading')return;const button=this;button.disabled=true;P.phase='loading';const epoch=++P.epoch;try{seedStarter();const chosen=$('deckSel').value!==''||$('codeIn').value.trim()?chosenDeck():starterDeck();validateDeck(chosen);let enemy=await opponentDeck(chosen);validateDeck(enemy);await preload([chosen,enemy]);if(epoch!==P.epoch)return;const autoAttack=Object.values(enemy.cards).some(c=>(D(c)?.attacks||[]).some(a=>attackInfo(slotOf(c),a,null,{hand:[]},true).auto&&parseDmg(a.damage)>0));if(!autoAttack)throw Error('이 AI 덱에는 자동 처리할 수 있는 공격이 없어요. 불꽃 스타터 덱으로 시작해 주세요.');const nick=$('nick').value.trim()||'트레이너';localStorage.setItem('dgpk_nick',nick);localStorage.setItem('dgpk_ailv',String(aiLv));P.speed=+$('aiSpeed').value;begin(chosen,enemy,nick);$('aiLoadStatus').textContent='';}catch(e){P.phase='idle';$('aiLoadStatus').textContent=e.message+'\n기본 연습 덱으로 다시 시작할 수 있어요.';}finally{button.disabled=false;button.textContent='AI 대전 시작';}};
$('resumeAI').onclick=function(){const s=localGet(SAVE,null);if(!s||s.version!==2)return;try{resetRuntime();Object.assign(dcache,s.cache);seedStarter();me=s.me;opp=s.opp;turn=s.turn;turnNo=s.turnNo;aiLv=s.aiLv;logs=s.logs||[];solo=true;ai=true;P.speed=s.speed||650;P.lastDecks=s.lastDecks||null;P.phase=s.phase;oppPub=pub(opp);$('lobby').classList.add('hide');$('game').classList.remove('hide');$('mewBtn').classList.remove('hide');sync();if(P.phase==='setup'&&!me.active)chooseStarting();if(P.phase==='promotion')choosePromotion();}catch(e){P.phase='idle';$('aiLoadStatus').textContent='저장된 경기를 불러오지 못했어요. 새 대전을 시작해 주세요.';}};
function selectCards(title,cards,done,opts={}){let selected=[];sheet('<h3>'+esc(title)+'</h3>'+(opts.note?'<p class="battle-note">'+esc(opts.note)+'</p>':'')+'<div class="list">'+cards.map((c,i)=>'<button type="button" class="c" data-choice="'+i+'" aria-pressed="false">'+imgTagOf(c)+'<div class="n">'+esc(c.name)+'</div></button>').join('')+'</div>'+(opts.count?'<button class="primary-wide" type="button" id="selectDone" disabled>선택 완료</button>':'')+(opts.mandatory?'':'<button type="button" class="ghost" style="width:100%;margin-top:10px" onclick="closeSheet()">취소</button>'));
 document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const c=cards[+b.dataset.choice];if(!opts.count){done([c]);return;}if(selected.includes(c))selected=selected.filter(x=>x!==c);else if(selected.length<opts.count)selected.push(c);document.querySelectorAll('[data-choice]').forEach(el=>el.setAttribute('aria-pressed',String(selected.includes(cards[+el.dataset.choice]))));$('selectDone').disabled=selected.length!==opts.count;$('selectDone').textContent=selected.length+' / '+opts.count+'장 선택 완료';});if(opts.count)$('selectDone').onclick=()=>done(selected);}
function chooseStarting(){selectCards('첫 배틀 포켓몬을 골라 주세요',me.hand.filter(isBasic),cards=>{if(P.phase!=='setup'||me.active)return;const c=cards[0],i=me.hand.indexOf(c);if(i<0)return;me.hand.splice(i,1);me.active=slotOf(c);closeSheet();log(c.name+' 배틀 준비');sync();},{mandatory:true,note:'벤치에 기본 포켓몬을 더 낸 뒤 [준비 완료]를 누르세요.'});}
$('btnReady').onclick=()=>{if(P.phase!=='setup'||!me.active)return;closeSheet();const first=rnd()<.5;me.first=first;opp.first=!first;players().forEach(p=>{if(p.bonusDraw){p.hand=p.hand.concat(p.deck.splice(0,p.bonusDraw));log(p.nick+' 멀리건 보상 '+p.bonusDraw+'장');p.bonusDraw=0;}});turnNo=1;log((first?me.nick:opp.nick)+' 선공');startActor(first?'me':'opp');};
function startActor(who){if(ended)return;turn=who;const p=who==='me'?me:opp;p.turns=(p.turns||0)+1;p.energyUsed=p.supporterUsed=p.attacked=p.retreated=p.stadiumUsed=false;p.drew=true;
 if(!p.deck.length){finish(who!=='me','턴 시작에 뽑을 카드가 없습니다.');return;}p.hand.push(p.deck.shift());log(p.nick+' 턴 시작 · 1장 자동 드로');P.phase=who==='me'?'player':'ai';P.step='';stopTimer();sync();if(who==='opp')runAI();else checkpoint();}
async function pausePoint(epoch){while(P.paused&&!ended&&epoch===P.epoch)await delay(100);return !ended&&epoch===P.epoch;}
$('pauseAI').onclick=()=>{if(!active()||ended)return;P.paused=!P.paused;render();};
window.canAct=function(){if(!active())return old.canAct();if(!canPlay()){toast(P.paused?'일시정지를 해제해 주세요':'지금은 카드를 사용할 수 없어요');return false;}return true;};
window.sync=function(){if(!active())return old.sync();oppPub=pub(opp);render();checkpoint();};
window.startTurn=function(){if(!active())return old.startTurn();startActor('me');};
window.enterGame=function(){return old.enterGame();};
window.aiCheckKO=function(){if(!active())return old.aiCheckKO();return settleKO();};
window.aiTurn=function(){if(!active())return old.aiTurn();return runAI();};
function choosePromotion(){if(me.active||!me.bench.length)return;selectCards('새 배틀 포켓몬을 골라 주세요',me.bench.map(topCard),cards=>{if(P.phase!=='promotion'||P.paused)return;const i=me.bench.findIndex(s=>topCard(s).uid===cards[0].uid);if(i<0)return;me.active=me.bench.splice(i,1)[0];closeSheet();log(me.active.stack.at(-1).name+' 배틀로');const resume=P.pendingPromotion;P.pendingPromotion=null;if(resume)resume();else{P.phase='player';turn='me';sync();}},{mandatory:true,note:'선택할 때까지 AI와 다음 턴 진행이 멈춥니다.'});}
async function settleKO(){if(ended)return;const losses=[[],[]];players().forEach((p,j)=>{field(p).forEach(s=>{if(s.dmg>=hpOf(s))losses[j].push(s);});});
 players().forEach((p,j)=>{losses[j].forEach(s=>{if(p.active===s)p.active=null;else p.bench.splice(p.bench.indexOf(s),1);p.discard.push(...allCards(s));const winner=j===0?opp:me;const n=Math.min(prizeCount(s),winner.prizes.length);winner.hand.push(...winner.prizes.splice(0,n));log(topCard(s).name+' 기절 · '+winner.nick+' 프라이즈 '+n+'장');});});
 const wins=[Number(me.prizes.length===0)+Number(!opp.active&&!opp.bench.length),Number(opp.prizes.length===0)+Number(!me.active&&!me.bench.length)];
 if(wins[0]||wins[1]){if(wins[0]===wins[1])finish(null,'동시에 승리 조건 충족 · 이번 연습은 무승부입니다.');else finish(wins[0]>wins[1],!me.prizes.length||!opp.prizes.length?'프라이즈를 모두 가져갔습니다.':'상대 필드에 포켓몬이 없습니다.');return;}
 if(!opp.active)aiPromote();if(!me.active){const previous=P.phase;P.phase='promotion';sync();await new Promise(resolve=>{P.pendingPromotion=resolve;choosePromotion();});if(ended)return;P.phase=previous;}
 sync();}
function checkup(actor){players().forEach(p=>{const s=p.active;if(!s)return;const st=s.status;if(st.poison){s.dmg+=10;log(topCard(s).name+' 독 +10');}if(st.burn){s.dmg+=20;if(rnd()<.5)st.burn=false;log(topCard(s).name+' 화상 +20'+(!st.burn?' · 회복':''));}if(st.asleep&&rnd()<.5){st.asleep=false;log(topCard(s).name+' 잠에서 깨어남');}if(p===actor&&st.paralyzed){st.paralyzed=false;log(topCard(s).name+' 마비 해제');}});}
async function finishTurn(who){if(ended||P.phase==='resolving'||P.phase==='promotion')return;const epoch=P.epoch;P.phase='resolving';closeSheet();sync();await settleKO();if(ended||epoch!==P.epoch)return;checkup(who==='me'?me:opp);await settleKO();if(ended||epoch!==P.epoch)return;turnNo++;startActor(who==='me'?'opp':'me');}
const oldEnd=$('btnEnd').onclick;$('btnEnd').onclick=e=>{if(!active())return oldEnd(e);e.preventDefault();if(!canPlay())return;sheet('<h3>턴을 종료할까요?</h3><p>'+(!me.energyUsed?'아직 에너지를 붙이지 않았어요. ':'')+'공격하지 않고 다음 턴으로 넘깁니다.</p><button type="button" class="primary-wide" id="endConfirm">턴 종료</button><button type="button" class="ghost" style="width:100%;margin-top:8px" onclick="closeSheet()">계속하기</button>');$('endConfirm').onclick=()=>{if(canPlay())finishTurn('me');};};
function finish(win,reason){if(ended)return;ended=true;P.phase='finished';P.epoch++;P.running=false;P.paused=false;stopTimer();clearTimeout(koTimer);if(P.pendingPromotion){P.pendingPromotion();P.pendingPromotion=null;}try{localStorage.removeItem(SAVE);}catch(e){}if(win!==null){const records=localGet('dgpk_ai_records',[]);records.push({t:Date.now(),lv:aiLv,win});localSet('dgpk_ai_records',records.slice(-100));}sync();const title=win===null?'무승부':win?'승리!':'수고했어요';sheet('<span class="eyebrow">PRACTICE COMPLETE</span><h3>'+title+'</h3><div class="result-score">'+(6-me.prizes.length)+' : '+(6-opp.prizes.length)+'</div><p>가져간 프라이즈 · '+turnNo+'턴 · AI Lv.'+aiLv+'</p><p class="battle-note">'+esc(reason)+'</p><button type="button" class="primary-wide" id="rematchAI">같은 덱으로 한 판 더</button><button type="button" class="ghost" style="width:100%;margin-top:8px" onclick="location.reload()">로비로</button>');$('rematchAI').onclick=()=>{let d=P.lastDecks;if(!d){const restoreDeck=p=>{const cards={};p.deck.concat(p.hand,p.prizes,p.discard,p.lost,p.stadium?[p.stadium]:[],field(p).flatMap(allCards)).forEach(c=>{if(!cards[c.id])cards[c.id]={id:c.id,name:c.name,img:c.img,n:0};cards[c.id].n++;});return {name:p.deckName,cards};};d={mine:restoreDeck(me),enemy:restoreDeck(opp),nick:me.nick};}begin(d.mine,d.enemy,d.nick);};}
window.gameOver=function(win,fromOpp){if(!active())return old.gameOver(win,fromOpp);finish(win,win?'승리 조건을 달성했습니다.':'대전이 종료되었습니다.');};
/* Shared attack evaluation: the same costs and arithmetic are used by both sides. */
function energyUnits(c){const d=D(c)||{},name=enName(c)+' '+c.name;if(d.energyType!=='Special')return [energyType(c)];if(/Double Colorless|더블 무색/i.test(name))return ['Colorless','Colorless'];if(/Rainbow Energy|레인보우 에너지/i.test(name))return ['*'];return ['Colorless'];}
function poolOf(slot){return slot.energy.flatMap(energyUnits);}
function missingCost(slot,cost){const pool=poolOf(slot);let missing=0,colorless=0;(cost||[]).forEach(type=>{if(type==='Colorless'){colorless++;return;}let i=pool.indexOf(type);if(i<0)i=pool.indexOf('*');if(i<0)missing++;else pool.splice(i,1);});return missing+Math.max(0,colorless-pool.length);}
window.canPay=(s,cost)=>active()?missingCost(s,cost)===0:old.canPay(s,cost);
window.energyGap=(s,cost)=>active()?missingCost(s,cost):old.energyGap(s,cost);
function weakDamage(amount,attacker,defender){if(!amount||!defender)return Math.max(0,amount);const d=D(topCard(defender))||{},types=typesOf(attacker);let n=amount;if([me?.active,opp?.active].includes(defender)&&(d.abilities||[]).some(a=>/attacks used by your opponent's Active Pokémon do 20 less damage \(before applying Weakness and Resistance\)/i.test(a.effect||'')))n=Math.max(0,n-20);(d.weaknesses||[]).forEach(w=>{if(!types.includes(w.type))return;const v=String(w.value||'×2');n=/[×x]/i.test(v)?n*(parseDmg(v)||2):n+parseDmg(v);});(d.resistances||[]).forEach(r=>{if(types.includes(r.type))n-=parseDmg(r.value)||30;});return Math.max(0,n);}
window.calcDmg=(s,a,d)=>active()?weakDamage(parseDmg(a.damage),s,d):old.calcDmg(s,a,d);
function attackInfo(slot,attack,defender,owner,simulate){let text=String(attack.effect||'').replace(/\s+/g,' ').trim(),remaining=text,damage=parseDmg(attack.damage);const r={auto:true,damage,status:null,self:0,heal:0,discard:0,discardType:null,draw:0,bench:0,block:false,notes:[]};
 function consume(re,fn){const m=remaining.match(re);if(m){fn(m);remaining=remaining.replace(re,'').trim();}}
 const symbol={R:'Fire',W:'Water',G:'Grass',L:'Lightning',P:'Psychic',F:'Fighting',D:'Darkness',M:'Metal'};
 consume(/This attack does (\d+) more damage for each (?:\{([A-Z])\} )?Energy attached to this Pokémon\.?/i,m=>damage+=+m[1]*slot.energy.filter(c=>!m[2]||energyUnits(c).includes(symbol[m[2]])).length);
 consume(/This attack does (\d+) less damage for each damage counter on this Pokémon\.?/i,m=>damage-=+m[1]*Math.floor(slot.dmg/10));
 consume(/This attack does (\d+) more damage for each damage counter on this Pokémon\.?/i,m=>damage+=+m[1]*Math.floor(slot.dmg/10));
 consume(/This attack does (\d+) damage for each card in your hand\.?/i,m=>damage=+m[1]*owner.hand.length);
 consume(/This Pokémon (?:also )?does (\d+) damage to itself\.?/i,m=>r.self=+m[1]);
 consume(/Heal (\d+) damage from this Pokémon\.?/i,m=>r.heal=+m[1]);
 consume(/Discard all Energy from this Pokémon\.?/i,()=>r.discard=99);
 consume(/Discard (an|\d+) (?:\{([A-Z])\} )?Energy from this Pokémon\.?/i,m=>{r.discard=m[1].toLowerCase()==='an'?1:+m[1];r.discardType=symbol[m[2]]||null;});
 consume(/Draw (\d+|a) cards?\.?/i,m=>r.draw=m[1].toLowerCase()==='a'?1:+m[1]);
 consume(/This attack also does (\d+) damage to each of your opponent's Benched Pokémon\.?(?: \(Don't apply Weakness and Resistance for Benched Pokémon\.\))?/i,m=>r.bench=+m[1]);
 consume(/(?:Your opponent's Active Pokémon|The Defending Pokémon) is now (Burned|Poisoned|Asleep|Paralyzed|Confused)\.?/i,m=>r.status={burned:'burn',poisoned:'poison',asleep:'asleep',paralyzed:'paralyzed',confused:'confused'}[m[1].toLowerCase()]);
 consume(/Flip a coin\. If tails, this attack does nothing\.?/i,()=>{if(simulate)damage*=.5;else if(rnd()>=.5){damage=0;r.self=r.heal=r.discard=r.draw=r.bench=0;r.status=null;r.notes.push('코인 뒷면 · 기술 실패');}});
 consume(/Flip a coin\. If heads, this attack does (\d+) more damage\.?/i,m=>damage+=simulate?+m[1]/2:(rnd()<.5?+m[1]:0));
 consume(/During your next turn, this Pokémon can't attack\.?/i,()=>r.block=true);
 // Unknown effect text is never silently treated as a complete automatic effect.
 r.auto=!remaining.replace(/[.\s]/g,'').length&&(!/[+×x-]/.test(String(attack.damage||''))||text!==remaining);
 r.damage=weakDamage(Math.max(0,damage),slot,defender);r.remaining=remaining;return r;}
P.attackInfo=attackInfo;
function attackBlocked(p){return !p.active||p.active.status.asleep||p.active.status.paralyzed||(p.active.blockUntil!=null&&p.active.blockUntil>=(p.turns||0));}
window.bestAttack=function(slot,def){if(!active())return old.bestAttack(slot,def);let best={atk:null,dmg:0,score:-Infinity};if(!slot)return best;const owner=field(opp).includes(slot)?opp:field(me).includes(slot)?me:opp;(D(topCard(slot))?.attacks||[]).forEach(a=>{if(!canPay(slot,a.cost))return;const r=attackInfo(slot,a,def,owner,true);if(!r.auto)return;let score=r.damage+r.bench*12/10-Math.min(slot.energy.length,r.discard)*14+r.heal*.2;if(def&&r.damage>=hpOf(def)-def.dmg)score+=500+prizeCount(def)*160;if(r.self>=hpOf(slot)-slot.dmg)score-=250;if(r.block)score-=35;if(aiLv<=3)score+=rnd()*45;if(!best.atk||score>best.score)best={atk:a,dmg:r.damage,score};});return best;};
function applyStatus(slot,status){if(!slot||!status)return;if(['asleep','paralyzed','confused'].includes(status))['asleep','paralyzed','confused'].forEach(k=>slot.status[k]=false);slot.status[status]=true;}
function discardAttackEnergy(p,slot,count,type){let left=count;for(let i=slot.energy.length-1;i>=0&&left>0;i--)if(!type||energyUnits(slot.energy[i]).includes(type)){p.discard.push(slot.energy.splice(i,1)[0]);left--;}}
async function executeAttack(who,attack,manual){const p=who==='me'?me:opp,enemy=who==='me'?opp:me,slot=p.active;if(!slot||!enemy.active||p.attacked||ended)return false;if(!canPay(slot,attack.cost)||attackBlocked(p)||turnNo===1&&p.first)return false;
 if(who==='me'&&!canPlay())return false;p.attacked=true;P.phase=who==='me'?'resolving':'ai';closeSheet();
 if(slot.status.confused&&rnd()>=.5){slot.dmg+=30;log(p.nick+' 혼란 · 자신에게 30');await settleKO();if(!ended){P.phase=who==='me'?'player':'ai';await finishTurn(who);}return true;}
 const r=manual||attackInfo(slot,attack,enemy.active,p,false);if(!r.auto&&!manual){p.attacked=false;P.phase=who==='me'?'player':'ai';return false;}
 if(manual&&manual.hits)manual.hits.forEach(h=>{const target=h.target<0?enemy.active:enemy.bench[h.target];if(target)target.dmg+=h.dmg;});else{enemy.active.dmg+=r.damage;enemy.bench.forEach(s=>s.dmg+=r.bench||0);}
 slot.dmg=Math.max(0,slot.dmg+(r.self||0)-(r.heal||0));discardAttackEnergy(p,slot,r.discard||0,r.discardType);p.hand.push(...p.deck.splice(0,r.draw||0));applyStatus(enemy.active,r.status);if(r.block)slot.blockUntil=p.turns+1;
 log(p.nick+' · '+topCard(slot).name+'의 '+attack.name+' → '+(manual?'수동 효과 처리':r.damage+' 데미지')+(r.notes?.length?' · '+r.notes.join(', '):''));fxHit(who==='me'?'o':'m',-1);sync();await settleKO();if(!ended){P.phase=who==='me'?'player':'ai';await finishTurn(who);}return true;}
const oldAttack=$('btnAttack').onclick;
$('btnAttack').onclick=e=>{if(!active())return oldAttack(e);e.preventDefault();if(!canPlay())return;if(!me.active||!opp.active)return;if(turnNo===1&&me.first){toast('선공 첫 턴은 공격할 수 없어요');return;}if(attackBlocked(me)){toast('상태이상 또는 이전 기술 효과로 공격할 수 없어요');return;}
 const attacks=D(topCard(me.active))?.attacks||[];sheet('<h3>'+esc(topCard(me.active).name)+' · 기술 선택</h3><p class="battle-note">에너지가 맞는 기술을 선택하면 공격하고 턴이 자동으로 끝납니다.</p>'+attacks.map((a,i)=>{const r=attackInfo(me.active,a,opp.active,me,true),pay=canPay(me.active,a.cost);return '<button type="button" class="atkrow" data-attack="'+i+'" '+(!pay?'disabled':'')+'><b>'+esc(a.name)+' · '+(a.cost||[]).map(KO).join(' ')+'</b><small>'+(pay?(r.auto?'예상 '+r.damage+' 데미지 (약점·저항 반영)':'카드 효과를 직접 확인하고 처리'):'에너지 '+missingCost(me.active,a.cost)+'개 부족')+'</small><span class="tag">'+(r.auto?'자동 처리':'수동 효과')+'</span></button>';}).join('')+'<button type="button" class="ghost" style="width:100%" onclick="closeSheet()">취소</button>');document.querySelectorAll('[data-attack]').forEach(b=>b.onclick=()=>{const a=attacks[+b.dataset.attack];const r=attackInfo(me.active,a,opp.active,me,true);if(r.auto)executeAttack('me',a);else manualAttack(a);});};
function manualAttack(attack){const targets=[opp.active].concat(opp.bench),attacker=me.active,openedTurn=turnNo;sheet('<h3>'+esc(attack.name)+' · 수동 효과</h3><p class="battle-note manual">이 기술의 효과는 자동 해석하지 못했어요. 아래에 최종 데미지를 입력하고, 에너지 트래시 등 추가 효과는 [효과 직접 처리]에서 먼저 처리하세요.</p><p>'+esc(attack.effect||'')+'</p>'+targets.map((s,i)=>'<label class="row">'+esc(topCard(s).name)+'<input type="number" min="0" step="10" data-manual-hit="'+(i-1)+'" value="'+(i===0?parseDmg(attack.damage):0)+'" style="max-width:90px"></label>').join('')+'<button type="button" class="primary-wide" id="manualAttackGo">입력한 효과 적용 · 턴 종료</button><button type="button" class="ghost" style="width:100%;margin-top:8px" onclick="closeSheet()">취소</button>');$('manualAttackGo').onclick=()=>{if(!canPlay()||me.active!==attacker||turnNo!==openedTurn||targets.some((s,i)=>s!==[opp.active].concat(opp.bench)[i]))return;const hits=Array.from(document.querySelectorAll('[data-manual-hit]')).map(el=>({target:+el.dataset.manualHit,dmg:Math.max(0,Math.min(9990,Math.round((+el.value||0)/10)*10))}));executeAttack('me',attack,{auto:true,hits});};}
/* Trainer actions commit only after all targets/costs have been selected. */
function kindOf(c){const n=(enName(c)+' '+c.name).toLowerCase();if(isBossCard(c))return 'boss';if(/professor.*research|박사의 연구/.test(n))return 'research';if(/youngster|반바지 꼬마/.test(n))return 'youngster';if(/iono|모야모/.test(n))return 'iono';if(/judge|심판/.test(n))return 'judge';if(/nemona|네모/.test(n))return 'draw3';if(/nest ball|네스트볼/.test(n))return 'nest';if(/ultra ball|하이퍼볼/.test(n))return 'ultra';if(/^switch | switch$|포켓몬 교체/.test(n))return 'switch';if(/rare candy|이상한사탕/.test(n))return 'candy';return 'manual';}
function supportAllowed(p){return !p.supporterUsed&&!(turnNo===1&&p.first);}
function spendTrainer(p,c){const i=p.hand.indexOf(c);if(i<0)return false;const d=D(c)||{};if(d.trainerType==='Supporter'&&!supportAllowed(p))return false;p.hand.splice(i,1);p.discard.push(c);if(d.trainerType==='Supporter')p.supporterUsed=true;log(p.nick+' · '+c.name+' 사용');return true;}
function drawEffect(p,n){p.hand.push(...p.deck.splice(0,Math.max(0,n)));}
function resolveDrawSupporter(p,enemy,kind){if(kind==='research'){p.discard.push(...p.hand);p.hand=[];drawEffect(p,7);}if(kind==='youngster'){p.deck=shuffle(p.deck.concat(p.hand));p.hand=[];drawEffect(p,5);}if(kind==='draw3')drawEffect(p,3);
 if(kind==='judge'){[p,enemy].forEach(x=>{x.deck=shuffle(x.deck.concat(x.hand));x.hand=[];drawEffect(x,4);});}if(kind==='iono'){[p,enemy].forEach(x=>{x.deck.push(...shuffle(x.hand));x.hand=[];drawEffect(x,x.prizes.length);});}}
window.playTrainer=function(i,supporter){if(!active())return old.playTrainer(i,supporter);if(!canAct())return;const c=me.hand[i];if(!c)return;const d=D(c)||{};if(d.trainerType==='Supporter'&&!supportAllowed(me)){toast('이번 턴에는 서포트를 사용할 수 없어요');return;}const kind=kindOf(c);const valid=()=>canPlay()&&me.hand.includes(c);
 if(kind==='boss')return old.playTrainer(i,true);
 if(['research','youngster','draw3','judge','iono'].includes(kind)){if(spendTrainer(me,c)){resolveDrawSupporter(me,opp,kind);closeSheet();sync();}return;}
 if(kind==='switch'){if(!me.active||!me.bench.length){toast('교체할 벤치가 없어요');return;}selectCards('교체할 포켓몬',me.bench.map(topCard),cards=>{const j=me.bench.findIndex(s=>topCard(s).uid===cards[0].uid);if(!valid()||j<0)return;if(spendTrainer(me,c)){switchBench(me,cards[0].uid,topCard(me.active).uid);closeSheet();sync();}});return;}
 if(kind==='nest'||kind==='ultra'){if(kind==='nest'&&me.bench.length>=5){toast('벤치가 가득 찼어요');return;}const pool=me.deck.filter(x=>D(x)?.category==='Pokemon'&&(kind!=='nest'||isBasic(x)));if(!pool.length){toast('덱에 가져올 포켓몬이 없어요');return;}const pickTarget=costs=>selectCards(kind==='nest'?'벤치에 낼 기본 포켓몬':'손패로 가져올 포켓몬',pool,cards=>{const chosen=cards[0];if(!valid()||!me.deck.includes(chosen)||costs.some(x=>!me.hand.includes(x)))return;if(!spendTrainer(me,c))return;costs.forEach(x=>{me.hand.splice(me.hand.indexOf(x),1);me.discard.push(x);});me.deck.splice(me.deck.indexOf(chosen),1);if(kind==='nest')me.bench.push(slotOf(chosen));else me.hand.push(chosen);shuffle(me.deck);log(chosen.name+(kind==='nest'?' 벤치로':' 손패로'));closeSheet();sync();});
  if(kind==='ultra'){if(me.hand.length<3){toast('하이퍼볼 외에 버릴 카드 2장이 필요해요');return;}selectCards('먼저 버릴 손패 2장',me.hand.filter(x=>x!==c),pickTarget,{count:2,note:'포켓몬 선택까지 마치면 비용과 효과를 함께 처리합니다.'});}else pickTarget([]);return;}
 sheet('<h3>'+esc(c.name)+' · 수동 효과</h3><p class="battle-note manual">이 카드 효과는 자동 처리되지 않습니다. 내용을 확인한 뒤 사용해 주세요.</p><p>'+esc(d.effect||'카드 설명을 확인해 주세요.')+'</p><button type="button" class="primary-wide" id="manualTrainer">카드 사용 · 효과 직접 처리</button><button type="button" class="ghost" style="width:100%;margin-top:8px" onclick="closeSheet()">취소</button>');$('manualTrainer').onclick=()=>{if(valid()&&spendTrainer(me,c)){sync();effectMenu();}};
};
function effectMenu(){if(!canAct())return;sheet('<h3>카드 효과 직접 처리</h3><p class="battle-note manual">방금 사용한 카드에 적힌 범위만 처리하세요.</p><div class="acts"><button class="soft" onclick="drawN(1)">1장 드로</button><button class="soft" onclick="searchDeck()">덱 검색</button><button class="soft" onclick="document.getElementById(\'btnBatchDiscard\').onclick()">손패 트래시</button><button class="soft" onclick="gustMenu()">상대 벤치 호출</button><button class="ghost" onclick="document.getElementById(\'btnCoin\').onclick({preventDefault:function(){}})">코인</button><button class="ghost" onclick="closeSheet()">처리 완료</button></div>');}
window.toActive=function(i){if(!active())return old.toActive(i);if(P.phase!=='setup'||me.active||P.paused)return;const c=me.hand[i];if(!c||!isBasic(c))return;me.hand.splice(i,1);me.active=slotOf(c);closeSheet();sync();};
window.toBench=function(i){if(!active())return old.toBench(i);if((P.phase!=='setup'&&!canPlay())||P.paused)return;const c=me.hand[i];if(!c||!isBasic(c)||me.bench.length>=5){toast('기본 포켓몬만 벤치 5마리까지 낼 수 있어요');return;}me.hand.splice(i,1);me.bench.push(slotOf(c));closeSheet();sync();};
window.attach=function(i,kind,from){if(!active())return old.attach(i,kind,from);if(!canAct())return;const c=me.hand[i],d=D(c)||{};if(!c)return;if(kind==='energy'&&me.energyUsed){toast('에너지는 한 턴에 1장 붙일 수 있어요');return;}let targets=field(me);if(kind==='evolve')targets=targets.filter(s=>turnNo>2&&s.turnPlayed!==turnNo&&s.turnEvolved!==turnNo&&String(topCard(s).name).toLowerCase()===String(d.evolveFrom).toLowerCase());if(kind==='tool')targets=targets.filter(s=>!s.tools.length);if(!targets.length){toast('지금 붙일 수 있는 포켓몬이 없어요');return;}
 selectCards(kind==='evolve'?'진화할 포켓몬':'카드를 붙일 포켓몬',targets.map(topCard),cards=>{if(!canPlay()||!me.hand.includes(c))return;const target=targets.find(s=>topCard(s).uid===cards[0].uid);if(!target||!field(me).includes(target))return;me.hand.splice(me.hand.indexOf(c),1);if(kind==='energy'){target.energy.push(c);me.energyUsed=true;}else if(kind==='tool')target.tools.push(c);else{target.stack.push(c);target.turnEvolved=turnNo;target.status={};delete target.blockUntil;}log(c.name+' → '+topCard(target).name);closeSheet();sync();});};
const originalSwitch=switchBench;window.switchBench=function(p,target,previous){const prior=p?.active;const ok=originalSwitch(p,target,previous);if(ok&&prior)delete prior.blockUntil;return ok;};
function payRetreat(p,s){const cost=Number(D(topCard(s))?.retreat??2);if(poolOf(s).length<cost)return false;let paid=0;while(paid<cost&&s.energy.length){const c=s.energy.pop();paid+=energyUnits(c).length;p.discard.push(c);}p.retreated=true;return true;}
window.retreat=function(){if(!active())return old.retreat();if(!canAct()||!me.active)return;if(me.retreated||me.active.status.asleep||me.active.status.paralyzed){toast('이번 턴에는 후퇴할 수 없어요');return;}const cost=Number(D(topCard(me.active))?.retreat??2);if(poolOf(me.active).length<cost){toast('후퇴 에너지가 '+cost+'개 필요해요');return;}const prior=me.active;selectCards('후퇴 후 배틀로 나올 포켓몬',me.bench.map(topCard),cards=>{if(!canPlay()||me.active!==prior)return;if(!me.bench.some(s=>topCard(s).uid===cards[0].uid))return;if(payRetreat(me,prior)){switchBench(me,cards[0].uid,topCard(prior).uid);closeSheet();sync();}},{note:'후퇴 비용 '+cost+'개를 트래시합니다. 후퇴는 한 턴에 1번입니다.'});};
window.promote=function(i){if(!active())return old.promote(i);if(P.phase==='promotion'){if(!me.bench[i])return;const c=topCard(me.bench[i]);const b=Array.from(document.querySelectorAll('[data-choice]')).find(el=>+el.dataset.choice===i);if(b)b.click();return;}if(me.active)return retreat();};
window.ko=function(i){if(!active())return old.ko(i);if(!canAct())return;const s=getSlot(i);if(!s)return;if(s.dmg<hpOf(s)){toast('남은 HP가 있어요. 효과로 기절했다면 데미지부터 조정해 주세요');return;}settleKO();};
window.prizeMenu=function(){if(!active())return old.prizeMenu();sheet('<h3>프라이즈 '+me.prizes.length+'장 남음</h3><p class="battle-note">AI전에서는 상대 포켓몬이 기절하면 프라이즈를 자동으로 가져옵니다.</p><button class="primary-wide" onclick="closeSheet()">확인</button>');};
window.drawN=function(n){if(!active())return old.drawN(n);if(!canAct())return;const count=Math.max(0,Math.min(60,Math.floor(Number(n)||0)));if(!count)return;const got=Math.min(count,me.deck.length);drawEffect(me,got);log('카드 효과 · '+got+'장 드로');sync();};
const oldDraw=$('btnDraw').onclick;$('btnDraw').onclick=e=>{if(!active())return oldDraw(e);toast('AI전의 턴 시작 드로는 자동이에요');};
window.handMenu=function(i){if(!active())return old.handMenu(i);if(P.phase==='promotion'){choosePromotion();return;}if(P.phase==='setup'||canPlay()){old.handMenu(i);const c=me.hand[i],b=$('sheetIn').querySelector('.preview button');if(c&&b)b.onclick=()=>cardDetail(c.id,c.name);return;}const c=me.hand[i];if(c)cardDetail(c.id,c.name);};
window.renderHandActs=function(i,c,d){if(!active())return old.renderHandActs(i,c,d);if(me.hand[i]!==c||!$('hmActs'))return;if(P.phase==='setup'){let h='';if(isBasic(c)){if(!me.active)h+='<button class="full" onclick="toActive('+i+')">첫 배틀 포켓몬으로</button>';if(me.bench.length<5)h+='<button class="soft full" onclick="toBench('+i+')">벤치에 내기</button>';}h+='<button class="ghost full" onclick="closeSheet()">닫기</button>';$('hmActs').innerHTML=h;return;}old.renderHandActs(i,c,d);if(d?.category==='Trainer'&&kindOf(c)==='manual')$('hmActs').insertAdjacentHTML('afterbegin','<p class="battle-note manual full">이 카드의 효과는 수동 처리합니다.</p>');};
// Read-only inspection stays available on the opponent's turn; mutation entry points are locked.
['playStadium','handTo','fieldTo','attachedView','dmg','tog','searchDeck'].forEach(name=>{const original=old[name];window[name]=function(){if(active()&&!canAct())return;return original.apply(this,arguments);};});
window.pileView=function(list,title,mine){return old.pileView(list,title,mine&&(!active()||canPlay()));};
window.mulligan=function(){if(active()){toast('첫 손패 멀리건은 시작할 때 자동으로 처리해요');return;}return old.mulligan();};
window.extraDraw=function(){if(active()){toast('멀리건 보상은 준비 완료 때 자동으로 받아요');return;}return old.extraDraw();};
window.fieldMenu=function(s,i){if(!active())return old.fieldMenu(s,i);if(P.phase==='promotion'){choosePromotion();return;}if(P.phase==='setup'||!canPlay()){cardDetail(topCard(s).id,topCard(s).name);return;}return old.fieldMenu(s,i);};
window.useAbility=function(i){if(active()&&!canAct())return;return old.useAbility(i);};
const oldMenu=$('btnMenu').onclick;$('btnMenu').onclick=e=>{if(!active())return oldMenu(e);e.preventDefault();sheet('<h3>AI 대전 메뉴</h3><div class="acts"><button class="soft full" id="openManual">효과 직접 처리</button><button class="soft" onclick="document.getElementById(\'btnLog\').onclick({preventDefault:function(){}})">대전 기록</button><button class="soft" onclick="document.getElementById(\'pauseAI\').onclick();closeSheet()">'+(P.paused?'계속하기':'일시정지')+'</button><button class="warn" onclick="concede()">항복</button><button class="ghost" onclick="location.reload()">저장하고 로비로</button></div><p style="font-size:12px;color:var(--ink2)">이어하기는 마지막 내 턴의 저장 상태에서 재개합니다. AI가 진행 중이면 직전 내 턴으로 돌아갑니다.</p>');$('openManual').onclick=effectMenu;};
function aiDrawSupporter(){if(!supportAllowed(opp))return;if(aiLv>=5&&opp.hand.some(isBossCard)&&aiBossTarget(true))return;const options=opp.hand.filter(c=>D(c)?.trainerType==='Supporter').map(c=>{const kind=kindOf(c);let score=0;if(kind==='research')score=(7-(opp.hand.length-1))*12;if(kind==='youngster')score=(5-(opp.hand.length-1))*12;if(kind==='draw3')score=30;if(kind==='judge')score=(4-(opp.hand.length-1))*8+(me.hand.length-4)*5;if(kind==='iono')score=(opp.prizes.length-(opp.hand.length-1))*8+(me.hand.length-me.prizes.length)*5;return {c,kind,score};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(options[0]&&spendTrainer(opp,options[0].c))resolveDrawSupporter(opp,me,options[0].kind);}
function aiItems(){const items=opp.hand.filter(c=>D(c)?.category==='Trainer'&&D(c)?.trainerType!=='Supporter');for(const c of items){if(!opp.hand.includes(c))continue;const kind=kindOf(c);
 if(kind==='nest'&&opp.bench.length<5){const pool=opp.deck.filter(isBasic).sort((a,b)=>aiBasicValue(b)-aiBasicValue(a));const chosen=aiLv<=2?pool[Math.floor(rnd()*pool.length)]:pool[0];if(chosen&&spendTrainer(opp,c)){opp.deck.splice(opp.deck.indexOf(chosen),1);opp.bench.push(slotOf(chosen));shuffle(opp.deck);log(chosen.name+' 벤치로');}}
 if(kind==='ultra'&&opp.hand.length>=3){const pool=opp.deck.filter(x=>D(x)?.category==='Pokemon');const evos=pool.filter(x=>field(opp).some(s=>String(D(x).evolveFrom||'').toLowerCase()===topCard(s).name.toLowerCase()));const chosen=evos[0]||(opp.bench.length<4?pool.filter(isBasic).sort((a,b)=>aiBasicValue(b)-aiBasicValue(a))[0]:null);if(!chosen)continue;const costs=opp.hand.filter(x=>x!==c).sort((a,b)=>aiCardValue(a)-aiCardValue(b)).slice(0,2);if(costs.length===2&&spendTrainer(opp,c)){costs.forEach(x=>{opp.hand.splice(opp.hand.indexOf(x),1);opp.discard.push(x);});opp.deck.splice(opp.deck.indexOf(chosen),1);opp.hand.push(chosen);shuffle(opp.deck);log(chosen.name+' 손패로');}}
 if(kind==='candy'){const stage2=opp.hand.filter(x=>D(x)?.stage==='Stage2');let applied=false;for(const evo of stage2){const target=field(opp).find(s=>aiCanCandy(s,evo));if(target&&spendTrainer(opp,c)){opp.hand.splice(opp.hand.indexOf(evo),1);target.stack.push(evo);target.status={};target.turnEvolved=turnNo;delete target.blockUntil;applied=true;break;}}if(applied)log('AI · 이상한사탕 진화');}
 }}
function aiSwitchOrRetreat(){if(!opp.active||!opp.bench.length||aiLv<4)return;const current=opp.active,currentAttack=attackBlocked(opp)?{atk:null,score:-Infinity,dmg:0}:bestAttack(current,me.active);const threat=me.active?bestAttack(me.active,current):{dmg:0};const alternatives=opp.bench.map(s=>({s,atk:bestAttack(s,me.active)})).filter(x=>x.atk.atk&&(!currentAttack.atk||x.atk.score>currentAttack.score+30||(aiLv>=7&&threat.dmg>=hpOf(current)-current.dmg&&x.atk.dmg>=currentAttack.dmg&&bestAttack(me.active,x.s).dmg<hpOf(x.s)-x.s.dmg))).sort((a,b)=>b.atk.score-a.atk.score);if(!alternatives.length)return;const target=alternatives[0].s,card=opp.hand.find(c=>kindOf(c)==='switch');if(card){if(!spendTrainer(opp,card))return;}else if(current.status.asleep||current.status.paralyzed||opp.retreated||!payRetreat(opp,current))return;switchBench(opp,topCard(target).uid,topCard(current).uid);log('AI · '+topCard(target).name+' 배틀로 교체');}
function aiAbilities(){if(aiLv<4)return;field(opp).forEach(s=>{if(s.abilityUsed===turnNo)return;const ab=D(topCard(s))?.abilities||[];for(const a of ab){const m=String(a.effect||'').match(/^Once during your turn, you may draw (\d+) cards?\.?$/i);if(m){drawEffect(opp,+m[1]);s.abilityUsed=turnNo;log('AI · '+a.name+' 특성');break;}}});}
async function runAI(){if(!active()||ended||turn!=='opp'||P.running)return;P.running=true;const epoch=P.epoch;P.phase='ai';const steps=[['필드와 진화 준비',()=>{aiDeployBasics();aiEvolve();}],['특성 확인',aiAbilities],['서포트 판단',aiDrawSupporter],['필요한 포켓몬 찾기',aiItems],['새 카드 전개',()=>{aiDeployBasics();aiEvolve();}],['공격 에너지 준비',()=>{if(opp.energyUsed)return;const plan=aiEnergyPlan();if(plan){opp.hand.splice(opp.hand.indexOf(plan.energy),1);plan.slot.energy.push(plan.energy);opp.energyUsed=true;log('AI · '+plan.energy.name+' → '+topCard(plan.slot).name);}}],['배틀 포켓몬 결정',aiSwitchOrRetreat],['보스의 지령 판단',()=>{if(aiLv<5||!supportAllowed(opp))return;const card=opp.hand.find(isBossCard),target=aiBossTarget(false);if(card&&target&&spendTrainer(opp,card)){switchBench(me,topCard(target.slot).uid,topCard(me.active).uid);log('AI · 보스의 지령 → '+topCard(me.active).name);}}]];
 try{for(const [name,fn] of steps){if(!await pausePoint(epoch))return;P.step=name;fn();sync();await delay(P.speed);if(epoch!==P.epoch||ended)return;}if(!await pausePoint(epoch))return;P.step='공격 선택';sync();const best=opp.active&&me.active?bestAttack(opp.active,me.active):{atk:null};if(best.atk&&!attackBlocked(opp)&&!(turnNo===1&&opp.first)){await executeAttack('opp',best.atk);}else{log('AI · '+(turnNo===1&&opp.first?'선공 첫 턴':attackBlocked(opp)?'상태이상으로 공격 불가':'사용 가능한 자동 기술 없음')+' · 턴 종료');await finishTurn('opp');}}
 catch(e){console.error(e);P.phase='error';P.step='AI 진행을 잠시 멈췄어요';render();sheet('<h3>진행 복구</h3><p>처리 중 오류가 발생했습니다. 현재 필드는 유지됩니다.</p><button class="primary-wide" id="recoverAI">현재 AI 턴을 종료하고 계속</button>');$('recoverAI').onclick=()=>{P.phase='ai';P.paused=false;finishTurn('opp');};}finally{P.running=false;}}
P.run=runAI;P.settleKO=settleKO;P.finishTurn=finishTurn;P.startActor=startActor;P.begin=begin;P.checkup=checkup;P.executeAttack=executeAttack;
/* Field information stays readable even if an image server is unavailable. */
window.slotHTML=function(s,mine,idx,isActive){if(!s)return '<div class="slot'+(isActive?' active':' empty-slot')+'" tabindex="0" role="button" aria-label="'+(isActive?'배틀 포켓몬 선택':'빈 벤치')+'" data-k="'+(mine?'m':'o')+'" data-i="'+idx+'">'+(isActive?'배틀 포켓몬':'＋')+'</div>';const c=topCard(s),hp=Number(D(c)?.hp)||0,left=Math.max(0,hp-s.dmg),low=hp>0&&left/hp<.35,status=Object.keys(s.status).filter(k=>s.status[k]).map(k=>STATUS[k]).join(' · ');return '<div class="slot'+(isActive?' active':'')+(low&&!isActive?' low':'')+'" tabindex="0" role="button" aria-label="'+esc(c.name)+' '+(hp?'HP '+left+'/'+hp:'데미지 '+s.dmg)+'" data-k="'+(mine?'m':'o')+'" data-i="'+idx+'"><div class="portrait">'+imgTagOf(c)+'</div><span class="slot-name">'+esc(c.name)+'</span><span class="hp-line">'+(hp?'HP '+left+' / '+hp:'피해 '+s.dmg)+'</span><span class="hp-meter"><i style="width:'+(hp?left/hp*100:100)+'%"></i></span>'+(s.dmg?'<span class="dmg">−'+s.dmg+'</span>':'')+(s.energy.length?'<span class="en">'+s.energy.map(e=>'<i title="'+esc(e.name)+'" style="background:'+({Fire:'#ef9367',Water:'#79b9ff',Grass:'#8eda7d',Psychic:'#c995ea',Lightning:'#f8d976',Darkness:'#66768b',Metal:'#b6c6d9'}[energyType(e)]||'#a6abb5')+'"></i>').join('')+'</span>':'')+(status?'<span class="st">'+status+'</span>':'')+'</div>';};
window.render=function(){if(!me)return;old.render();if(!(oppPub?.bench||[]).length)$('oBench').innerHTML='<span class="empty-bench">아직 벤치 포켓몬이 없어요</span>';$('mBenchCount').textContent=me.bench.length+'/5';$('oBenchCount').textContent=(oppPub?.bench||[]).length+'/5';$('handCount').textContent='내 손패 '+me.hand.length+'장';$('actionFlags').textContent='에너지 '+(me.energyUsed?'사용함':'가능')+' · 서포트 '+(me.supporterUsed?'사용함':'가능');document.querySelectorAll('#mHand .c').forEach(el=>{const c=me.hand[+el.dataset.i];if(c){el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',c.name);el.insertAdjacentHTML('beforeend','<span class="hand-name">'+esc(c.name)+'</span>');}});document.querySelectorAll('.slot,#mHand .c').forEach(el=>el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click();}});
 const isAI=active();document.querySelector('.tools').classList.toggle('ai-tools',isAI);$('pauseAI').classList.toggle('hide',!isAI||ended);$('pauseAI').textContent=P.paused?'계속하기':'일시정지';$('btnReady').classList.toggle('hide',!isAI||P.phase!=='setup');$('btnReady').disabled=!me.active||P.paused;$('btnSwap').classList.toggle('hide',!solo||ai);
 if(!isAI){$('phaseTag').textContent='BATTLE ROOM';$('phaseTitle').textContent=turn==='me'?'내 차례':'상대 차례';$('phaseHint').textContent='카드를 누르면 상세와 행동을 볼 수 있어요.';return;}
 const names={setup:['STARTING SETUP','첫 배틀 포켓몬을 준비하세요','손패에서 기본 포켓몬을 배틀·벤치에 놓고 [준비 완료].'],player:['YOUR TURN','내 차례 · '+me.turns+'번째 턴','드로 완료 · 에너지 → 카드 효과 → 공격'],ai:['AI TURN',P.step||'AI가 생각하고 있어요','AI 행동은 아래 기록에 차례대로 표시됩니다.'],promotion:['CHOOSE POKÉMON','새 배틀 포켓몬을 골라 주세요','벤치 포켓몬을 선택하면 멈춘 진행이 이어집니다.'],resolving:['RESOLVING','기절·상태이상 확인 중','효과 처리가 끝나면 다음 턴으로 넘어갑니다.'],finished:['MATCH COMPLETE','대전 종료','결과를 확인하거나 같은 덱으로 다시 도전하세요.'],error:['PAUSED','진행 복구가 필요해요','메시지를 확인하고 계속 진행할 수 있어요.']};const status=names[P.phase]||names.ai;$('phaseTag').textContent=status[0];$('phaseTitle').textContent=P.paused?'일시정지':status[1];$('phaseHint').textContent=P.paused?'[계속하기]를 누르면 이어집니다.':status[2];$('phaseTitle').onclick=P.phase==='promotion'?choosePromotion:P.phase==='setup'&&!me.active?chooseStarting:null;
 $('btnAttack').disabled=!canPlay()||!me.active||!opp.active||attackBlocked(me)||turnNo===1&&me.first;$('btnEnd').disabled=!canPlay();$('btnBatchDiscard').disabled=!canPlay();$('btnAttack').textContent='공격하기';$('btnMenu').textContent='⋯';$('btnEnd').textContent='턴 종료';
};
window.coach=function(){if(!active())return old.coach();if(!me)return;recSet={};if(canPlay())me.hand.forEach(c=>{const d=D(c);if(d?.category==='Energy'&&!me.energyUsed||isBasic(c)&&me.bench.length<5||d?.trainerType==='Supporter'&&supportAllowed(me))recSet[c.uid]=1;});markRec();};
const oldCoach=$('mewBtn').onclick;$('mewBtn').onclick=e=>{if(!active())return oldCoach(e);e.preventDefault();sheet('<h3>지금 무엇을 하면 될까요?</h3><div class="hint"><b>'+esc($('phaseTitle').textContent)+'</b>'+esc($('phaseHint').textContent)+'</div><div class="hint"><b>에너지는 한 턴에 1장</b>공격에 필요한 타입과 개수를 확인해서 붙이세요.</div><div class="hint"><b>공격하면 턴이 끝나요</b>벤치 준비와 서포트 사용을 먼저 마치세요.</div><div class="hint"><b>자동 / 수동 효과</b>기본 연습 덱은 자동 처리됩니다. 미지원 카드는 수동 효과 표시를 확인하세요.</div><button class="primary-wide" onclick="closeSheet()">확인</button>');};
const oldDeckMenu=deckMenu;window.deckMenu=function(){if(active()&&!canAct())return;return oldDeckMenu();};
const oldStadiumMenu=stadiumMenu;window.stadiumMenu=function(){if(active()&&!canAct())return;return oldStadiumMenu();};
const oldDevolve=devolve;window.devolve=function(i){if(active()&&!canAct())return;return oldDevolve(i);};
const oldClose=closeSheet;window.closeSheet=function(){if(active()&&P.phase==='promotion'&&!me.active)return;return oldClose();};
// Avoid firing a delayed card action after a turn changes or an AI step has started.
const originalSheet=sheet;window.sheet=function(html){return originalSheet(html);};
showResume();$('timerSel').value='0';
$('aiLv').oninput=function(){aiLv=Math.max(1,Math.min(10,+this.value||6));$('aiLvTxt').textContent='Lv.'+aiLv;$('aiDesc').textContent=aiLv<=3?'입문 · 기본 공격과 벤치 준비':aiLv<=6?'보통 · 에너지 배분과 보스 타이밍':'도전 · 프라이즈 우선, 공격 준비, 후퇴 판단';};$('aiLv').oninput();
// Put AI practice first without changing IDs used by existing multiplayer setup.
const aiBox=$('btnAI').closest('.box');$('lobby').insertBefore(aiBox,$('lobby').querySelector('.box'));

const originalImageTag=imgTagOf;
const failedImages=new Set();
function fallbackCard(c,cls){const d=D(c)||{},category=d.category||'Pokemon';const type=category==='Energy'?'에너지':category==='Trainer'?'트레이너':KO((d.types||[])[0]||'Pokemon');return '<div class="noimg fallback-card '+(category==='Energy'?'energy-card':category==='Trainer'?'trainer-card':'')+' '+(cls||'')+'"><span class="fallback-type">'+esc(type)+'</span><span class="fallback-mark">'+(category==='Energy'?'◉':category==='Trainer'?'◆':'◈')+'</span><span class="fallback-title">'+esc(c.name)+'</span></div>';}
window.imgTagOf=function(c,q,cls){if(!c.img||failedImages.has(c.id))return fallbackCard(c,cls);return originalImageTag(c,q,cls).replace('<img ','<img data-cardid="'+esc(c.id)+'" ');};
window.imgFallback=function(el){const id=el.dataset.cardid;if(id){failedImages.add(id);const c={id,name:el.dataset.name};el.outerHTML=fallbackCard(c,el.className);return;}el.dataset.broken='true';el.style.visibility='hidden';};
function helperFallback(){const img=$('mewBtn').querySelector('img');if(img)img.style.display='none';$('mewBtn').style.color='#273653';if(!$('mewBtn').querySelector('.helper-label'))$('mewBtn').insertAdjacentHTML('beforeend','<b class="helper-label">?</b>');}
const helperImage=$('mewBtn').querySelector('img');if(helperImage){helperImage.onerror=helperFallback;if(helperImage.complete&&!helperImage.naturalWidth)helperFallback();}
$('sheetIn').addEventListener('click',function(e){if(!active())return;const button=e.target.closest('button');if(!button)return;const code=button.getAttribute('onclick')||'';if(/(?:dmg\(|tog\(|fieldTo\(|devolve\(|me\.discard|me\.deck|me\.hand)/.test(code)&&!canPlay()){e.preventDefault();e.stopImmediatePropagation();toast('내 차례에 처리해 주세요');}},true);
['btnHost','btnJoin'].forEach(id=>{const handler=$(id).onclick;$(id).onclick=function(e){if(typeof Peer==='undefined'){toast('친구 대전 연결 모듈을 불러오는 중이에요. 잠시 뒤 다시 눌러 주세요');return;}return handler.call(this,e);};});
})();
